"""Track-package and compiled-centreline types for real circuits (A16).

These models are the Python authority for
``new_plan/17_real_tracks_conditions/track-package.schema.json``. They are
coordinator-owned and frozen: the ten A16 workers build on them and propose
changes through ``handoffs/``; they do not edit this file.

Two rules from the specification are enforced structurally rather than left
to discipline:

* **Readiness is derived from evidence, never set by hand.** A package cannot
  declare itself ``simulation_eligible`` while its corridor is ``unknown`` or its
  event overlay is absent; the validator refuses the object.
* **A real circuit does not make the run real.** Geometry may be genuine while
  every car and battery parameter stays a labelled synthetic assumption. The
  package carries ``geometry_provenance`` and the scenario carries the
  ``real_circuit_synthetic_energy`` label; nothing here can combine them into a
  claim of measured fidelity.
"""

from __future__ import annotations

import hashlib
import json
import math
from enum import StrEnum
from pathlib import Path
from typing import Any

import numpy as np
from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_VERSION = "1"
"""Matches ``track-package.schema.json`` ``schema_version`` const."""

CANONICAL_SPACING_M = 1.0
"""Canonical storage spacing from TRACK_DATA_PIPELINE.md step 5."""


class ReadinessStatus(StrEnum):
    """Track readiness ladder from TRACK_REGISTRY_2026.md.

    Each rung requires the evidence of the rung below it; the validator
    computes the rung from evidence and a hand-edited status is rejected.
    """

    DISCOVERED = "discovered"
    GEOMETRY_VALIDATED = "geometry_validated"
    EVENT_RULES_VALIDATED = "event_rules_validated"
    CONDITION_CALIBRATED = "condition_calibrated"
    SIMULATION_ELIGIBLE = "simulation_eligible"
    REJECTED = "rejected"


READINESS_ORDER: tuple[ReadinessStatus, ...] = (
    ReadinessStatus.DISCOVERED,
    ReadinessStatus.GEOMETRY_VALIDATED,
    ReadinessStatus.EVENT_RULES_VALIDATED,
    ReadinessStatus.CONDITION_CALIBRATED,
    ReadinessStatus.SIMULATION_ELIGIBLE,
)


def readiness_rank(status: ReadinessStatus) -> int:
    """Position on the ladder; ``rejected`` ranks below ``discovered``."""
    if status is ReadinessStatus.REJECTED:
        return -1
    return READINESS_ORDER.index(status)


class CorridorQuality(StrEnum):
    """How the left/right usable corridor was obtained."""

    SURVEYED = "surveyed"
    VALIDATED_ESTIMATE = "validated_estimate"
    UNKNOWN = "unknown"


class Direction(StrEnum):
    CLOCKWISE = "clockwise"
    COUNTERCLOCKWISE = "counterclockwise"
    MIXED = "mixed"


class GeometryProvenance(StrEnum):
    """Where the metric centreline came from, in the pipeline's priority order.

    ``synthetic_sketch`` is the existing fixture value used by ``TrackConfig``;
    it is included so one enum covers both track kinds.
    """

    LICENSED_SURVEY = "licensed_survey"
    OPENF1_LOCATION_TELEMETRY = "openf1_location_telemetry"
    FASTF1_POSITION_TELEMETRY = "fastf1_position_telemetry"
    OSM_CROSSCHECK_ONLY = "osm_crosscheck_only"
    SYNTHETIC_SKETCH = "synthetic_sketch"


class _Frozen(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid", str_strip_whitespace=True)


class SourceRecord(_Frozen):
    """One raw input, hashed and permission-labelled (TRACK_DATA_PIPELINE.md)."""

    source_id: str = Field(min_length=1)
    title: str = Field(min_length=1)
    url: str = Field(min_length=1)
    retrieved_at: str = Field(min_length=1, description="ISO-8601 UTC.")
    sha256: str | None = Field(default=None, pattern=r"^[a-f0-9]{64}$")
    permission: str = Field(min_length=1)
    priority: int | None = Field(
        default=None,
        ge=1,
        le=5,
        description="Source priority from TRACK_DATA_PIPELINE.md; 1 is an FIA event document.",
    )
    document_revision: str | None = None
    locator: str | None = Field(default=None, description="Page, field or session/driver/lap locator.")
    reviewer: str | None = None


class SRange(_Frozen):
    start_s_m: float = Field(ge=0.0)
    end_s_m: float = Field(ge=0.0)


class NamedRange(SRange):
    id: str = Field(min_length=1)


class GeometryDescriptor(_Frozen):
    sample_spacing_m: float = Field(gt=0.0)
    point_count: int = Field(ge=0)
    crs: str | None = None
    arrays_path: str | None = None
    corridor_quality: CorridorQuality = CorridorQuality.UNKNOWN
    provenance: GeometryProvenance = GeometryProvenance.SYNTHETIC_SKETCH
    arrays_sha256: str | None = Field(default=None, pattern=r"^[a-f0-9]{64}$")


class TrackFeatures(_Frozen):
    start_finish_s_m: float = Field(ge=0.0)
    sectors: tuple[SRange, ...] = ()
    corners: tuple[NamedRange, ...] = ()
    pit_lane_excluded: bool = True


class PowerCurveRow(_Frozen):
    """One breakpoint of an event Power Unit Information curve, as transcribed."""

    speed_kph: float = Field(ge=0.0)
    power_kw: float = Field(ge=0.0)


class EventOverlay(_Frozen):
    """Event-specific FIA lines, zones and parameters.

    Every numeric value here must have been confirmed by two reviewers against
    the hashed FIA document; ``review_status`` says whether that has happened.
    An unreviewed overlay is stored so the queue is visible, but the rules
    engine treats its lines as *unknown*, never as permissions.
    """

    event_id: str = Field(min_length=1)
    ruleset_hash: str = Field(min_length=1)
    fia_documents: tuple[SourceRecord, ...] = ()
    detection_lines_m: tuple[float, ...] = ()
    activation_lines_m: tuple[float, ...] = ()
    straight_mode_ranges: tuple[SRange, ...] = ()
    standard_curve: tuple[PowerCurveRow, ...] = ()
    overtake_curve: tuple[PowerCurveRow, ...] = ()
    recharge_allowance_mj: float | None = Field(default=None, ge=0.0)
    race_laps: int | None = Field(default=None, ge=1)
    review_status: str = Field(
        default="unreviewed",
        pattern=r"^(unreviewed|one_reviewer|confirmed|recalled)$",
    )
    reviewers: tuple[str, ...] = ()
    unknown_fields: tuple[str, ...] = Field(
        default=(),
        description="Fields the reviewers could not read or confirm; they resolve to unknown downstream.",
    )
    overlay_hash: str | None = Field(
        default=None,
        pattern=r"^[a-f0-9]{64}$",
        description=(
            "SHA-256 of this overlay's canonical JSON, written once at ingest and at each review "
            "step. A consumer that needs the overlay's identity reads this rather than recomputing "
            "it, so two call sites cannot disagree about what the overlay is."
        ),
    )

    @model_validator(mode="after")
    def _confirmed_requires_two_reviewers(self) -> EventOverlay:
        if self.review_status == "confirmed" and len(set(self.reviewers)) < 2:
            raise ValueError("a confirmed event overlay requires two distinct reviewers")
        return self

    def content_hash(self) -> str:
        """SHA-256 of the canonical JSON *excluding* ``overlay_hash`` itself."""
        payload = self.model_dump(mode="json", exclude={"overlay_hash"})
        text = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    def with_hash(self) -> EventOverlay:
        """The same overlay carrying its own content hash."""
        return self.model_copy(update={"overlay_hash": self.content_hash()})

    @property
    def is_confirmed(self) -> bool:
        return self.review_status == "confirmed"


class ValidationReport(_Frozen):
    """Evidence the readiness status is derived from (VALIDATION.md)."""

    status: ReadinessStatus
    closure_error_m: float | None = Field(default=None, ge=0.0)
    length_error_fraction: float | None = Field(default=None, ge=0.0)
    report_path: str | None = None
    official_length_m: float | None = Field(default=None, gt=0.0)
    checks: dict[str, str] = Field(
        default_factory=dict,
        description="check id -> pass | fail | unknown, from the independent validator.",
    )
    notes: tuple[str, ...] = ()


class TrackPackage(_Frozen):
    """The compiled, hash-pinned identity of one physical circuit."""

    schema_version: str = SCHEMA_VERSION
    track_id: str = Field(min_length=1, pattern=r"^[a-z0-9-]+$")
    display_name: str = Field(min_length=1)
    direction: Direction
    nominal_length_m: float = Field(gt=0.0)
    geometry: GeometryDescriptor
    features: TrackFeatures
    event_overlay: EventOverlay | None = None
    sources: tuple[SourceRecord, ...] = Field(min_length=1)
    validation: ValidationReport
    package_hash: str | None = Field(default=None, pattern=r"^[a-f0-9]{64}$")

    @model_validator(mode="after")
    def _readiness_is_earned(self) -> TrackPackage:
        """The ladder cannot be climbed by editing a field."""
        status = self.validation.status
        if status is ReadinessStatus.REJECTED:
            return self
        rank = readiness_rank(status)

        if rank >= readiness_rank(ReadinessStatus.GEOMETRY_VALIDATED):
            if self.geometry.point_count == 0 or self.geometry.arrays_path is None:
                raise ValueError(f"{status} requires compiled geometry arrays")
            if self.validation.closure_error_m is None or self.validation.length_error_fraction is None:
                raise ValueError(f"{status} requires measured closure and length errors")
        if rank >= readiness_rank(ReadinessStatus.EVENT_RULES_VALIDATED) and (
            self.event_overlay is None or not self.event_overlay.is_confirmed
        ):
            raise ValueError(f"{status} requires a two-reviewer confirmed event overlay")
        if (
            rank >= readiness_rank(ReadinessStatus.SIMULATION_ELIGIBLE)
            and self.geometry.corridor_quality is CorridorQuality.UNKNOWN
        ):
            raise ValueError("simulation_eligible requires a surveyed or validated corridor")
        return self

    def content_hash(self) -> str:
        """SHA-256 of the canonical JSON *excluding* ``package_hash`` itself."""
        payload = self.model_dump(mode="json", exclude={"package_hash"})
        text = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    def with_hash(self) -> TrackPackage:
        return self.model_copy(update={"package_hash": self.content_hash()})

    @property
    def is_simulation_eligible(self) -> bool:
        return self.validation.status is ReadinessStatus.SIMULATION_ELIGIBLE

    @property
    def lateral_geometry_known(self) -> bool:
        return self.geometry.corridor_quality is not CorridorQuality.UNKNOWN

    def to_schema_dict(self) -> dict[str, Any]:
        """The JSON shape ``track-package.schema.json`` validates."""
        return self.model_dump(mode="json")


class CompiledCentreline:
    """Dense periodic centreline arrays at canonical 1 m spacing.

    All arrays share one length ``n`` and are indexed by sample ``i`` at arc
    length ``s[i]``. Interpolation is periodic on ``[0, length_m)``. Curvature is
    signed with positive turning left, grade is ``dz/ds`` in radians, and the
    corridor half-widths are metres from the centreline; they are ``nan`` when
    the corridor quality is unknown so nothing downstream can read a number.
    """

    __slots__ = (
        "curvature_1pm",
        "grade_rad",
        "length_m",
        "mu",
        "s_m",
        "width_left_m",
        "width_right_m",
        "x_m",
        "y_m",
        "yaw_rad",
        "z_m",
    )

    def __init__(
        self,
        *,
        s_m: np.ndarray,
        x_m: np.ndarray,
        y_m: np.ndarray,
        z_m: np.ndarray,
        yaw_rad: np.ndarray,
        curvature_1pm: np.ndarray,
        grade_rad: np.ndarray,
        length_m: float,
        width_left_m: np.ndarray | None = None,
        width_right_m: np.ndarray | None = None,
        mu: np.ndarray | None = None,
    ) -> None:
        arrays = [s_m, x_m, y_m, z_m, yaw_rad, curvature_1pm, grade_rad]
        n = len(s_m)
        if n < 4:
            raise ValueError("a centreline needs at least four samples")
        if any(len(a) != n for a in arrays):
            raise ValueError("centreline arrays must share one length")
        if length_m <= 0.0 or not math.isfinite(length_m):
            raise ValueError("length_m must be positive and finite")
        if np.any(np.diff(s_m) <= 0.0):
            raise ValueError("s_m must be strictly increasing")
        if s_m[0] != 0.0 or s_m[-1] >= length_m:
            raise ValueError("s_m must start at 0 and end before length_m")
        for name, arr in (
            ("x", x_m),
            ("y", y_m),
            ("z", z_m),
            ("yaw", yaw_rad),
            ("curvature", curvature_1pm),
            ("grade", grade_rad),
        ):
            if not np.all(np.isfinite(arr)):
                raise ValueError(f"{name} contains a non-finite value")
        nan = np.full(n, np.nan, dtype=np.float64)
        self.s_m = np.asarray(s_m, dtype=np.float64)
        self.x_m = np.asarray(x_m, dtype=np.float64)
        self.y_m = np.asarray(y_m, dtype=np.float64)
        self.z_m = np.asarray(z_m, dtype=np.float64)
        self.yaw_rad = np.asarray(yaw_rad, dtype=np.float64)
        self.curvature_1pm = np.asarray(curvature_1pm, dtype=np.float64)
        self.grade_rad = np.asarray(grade_rad, dtype=np.float64)
        self.length_m = float(length_m)
        self.width_left_m = nan if width_left_m is None else np.asarray(width_left_m, dtype=np.float64)
        self.width_right_m = nan if width_right_m is None else np.asarray(width_right_m, dtype=np.float64)
        self.mu = np.full(n, np.nan) if mu is None else np.asarray(mu, dtype=np.float64)

    # -- periodic interpolation ------------------------------------------- #

    def _wrap(self, s_m: np.ndarray | float) -> np.ndarray:
        return np.asarray(s_m, dtype=np.float64) % self.length_m

    def _periodic(self, table: np.ndarray, s_m: np.ndarray | float) -> np.ndarray:
        s = self._wrap(s_m)
        xs = np.concatenate((self.s_m, [self.length_m]))
        ys = np.concatenate((table, [table[0]]))
        return np.interp(s, xs, ys)

    def _periodic_angle(self, table: np.ndarray, s_m: np.ndarray | float) -> np.ndarray:
        """Interpolate an angle through its sine and cosine to avoid wrap seams."""
        c = self._periodic(np.cos(table), s_m)
        sn = self._periodic(np.sin(table), s_m)
        return np.arctan2(sn, c)

    def curvature_at(self, s_m: float) -> float:
        return float(self._periodic(self.curvature_1pm, s_m))

    def grade_at(self, s_m: float) -> float:
        return float(self._periodic(self.grade_rad, s_m))

    def yaw_at(self, s_m: float) -> float:
        return float(self._periodic_angle(self.yaw_rad, s_m))

    def position_at(self, s_m: float) -> tuple[float, float, float]:
        return (
            float(self._periodic(self.x_m, s_m)),
            float(self._periodic(self.y_m, s_m)),
            float(self._periodic(self.z_m, s_m)),
        )

    def curvature_array(self, s_m: np.ndarray) -> np.ndarray:
        return self._periodic(self.curvature_1pm, s_m)

    def grade_array(self, s_m: np.ndarray) -> np.ndarray:
        return self._periodic(self.grade_rad, s_m)

    def width_at(self, s_m: float) -> float:
        """Total usable width. ``nan`` when the corridor is unknown."""
        left = float(self._periodic(self.width_left_m, s_m))
        right = float(self._periodic(self.width_right_m, s_m))
        return left + right

    @property
    def corridor_known(self) -> bool:
        return bool(np.all(np.isfinite(self.width_left_m)) and np.all(np.isfinite(self.width_right_m)))

    @property
    def point_count(self) -> int:
        return len(self.s_m)

    @property
    def closure_error_m(self) -> float:
        """Straight-line distance between the last sample advanced to ``length_m`` and the first."""
        # Advance the last sample by the remaining arc along its yaw.
        remaining = self.length_m - float(self.s_m[-1])
        x_end = float(self.x_m[-1]) + remaining * math.cos(float(self.yaw_rad[-1]))
        y_end = float(self.y_m[-1]) + remaining * math.sin(float(self.yaw_rad[-1]))
        return math.hypot(x_end - float(self.x_m[0]), y_end - float(self.y_m[0]))

    # -- persistence ------------------------------------------------------- #

    def to_npz(self, path: Path) -> str:
        """Write arrays atomically; return the SHA-256 of the file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        staging = path.with_suffix(path.suffix + ".staging")
        with staging.open("wb") as handle:
            np.savez(
                handle,
                s_m=self.s_m,
                x_m=self.x_m,
                y_m=self.y_m,
                z_m=self.z_m,
                yaw_rad=self.yaw_rad,
                curvature_1pm=self.curvature_1pm,
                grade_rad=self.grade_rad,
                width_left_m=self.width_left_m,
                width_right_m=self.width_right_m,
                mu=self.mu,
                length_m=np.asarray([self.length_m]),
            )
        staging.replace(path)
        return hashlib.sha256(path.read_bytes()).hexdigest()

    @classmethod
    def from_npz(cls, path: Path) -> CompiledCentreline:
        with np.load(path) as data:
            return cls(
                s_m=data["s_m"],
                x_m=data["x_m"],
                y_m=data["y_m"],
                z_m=data["z_m"],
                yaw_rad=data["yaw_rad"],
                curvature_1pm=data["curvature_1pm"],
                grade_rad=data["grade_rad"],
                length_m=float(data["length_m"][0]),
                width_left_m=data["width_left_m"],
                width_right_m=data["width_right_m"],
                mu=data["mu"],
            )

    def content_hash(self) -> str:
        digest = hashlib.sha256()
        for arr in (
            self.s_m,
            self.x_m,
            self.y_m,
            self.z_m,
            self.yaw_rad,
            self.curvature_1pm,
            self.grade_rad,
            self.width_left_m,
            self.width_right_m,
            self.mu,
        ):
            digest.update(np.ascontiguousarray(arr).tobytes())
        digest.update(repr(self.length_m).encode())
        return digest.hexdigest()


__all__ = [
    "CANONICAL_SPACING_M",
    "READINESS_ORDER",
    "SCHEMA_VERSION",
    "CompiledCentreline",
    "CorridorQuality",
    "Direction",
    "EventOverlay",
    "GeometryDescriptor",
    "GeometryProvenance",
    "NamedRange",
    "PowerCurveRow",
    "ReadinessStatus",
    "SRange",
    "SourceRecord",
    "TrackFeatures",
    "TrackPackage",
    "ValidationReport",
    "readiness_rank",
]
