"""Public persistence adapter surface."""

from __future__ import annotations

from .engine import (
    DEFAULT_SQLITE_NAME,
    SQLITE_BUSY_TIMEOUT_MS,
    command_transaction,
    create_all,
    create_db_engine,
    create_session_factory,
    default_database_url,
    drop_all,
    ensure_schema,
    sqlite_path,
    transaction,
)
from .models import Base
from .repository import (
    CommandOutcome,
    LifecycleError,
    acquire_lease,
    append_event,
    apply_operator_action,
    body_hash_of,
    claim_experiment_job,
    expire_due,
    invalidate_outstanding,
    mark_published,
    mark_published_batch,
    next_sequence,
    record_execution,
    require_lease,
    store_decision,
    unpublished_outbox,
)

__all__ = [
    "DEFAULT_SQLITE_NAME",
    "SQLITE_BUSY_TIMEOUT_MS",
    "Base",
    "CommandOutcome",
    "LifecycleError",
    "acquire_lease",
    "append_event",
    "apply_operator_action",
    "body_hash_of",
    "claim_experiment_job",
    "command_transaction",
    "create_all",
    "create_db_engine",
    "create_session_factory",
    "default_database_url",
    "drop_all",
    "ensure_schema",
    "expire_due",
    "invalidate_outstanding",
    "mark_published",
    "mark_published_batch",
    "next_sequence",
    "record_execution",
    "require_lease",
    "sqlite_path",
    "store_decision",
    "transaction",
    "unpublished_outbox",
]
