"""AFTERLAP wire contracts, contract revision 1.

This package is the single schema authority. Python models here generate the
JSON Schema and TypeScript declarations under ``packages/contracts/generated``.
Workers consume these types; only the coordinator changes them.
"""

from __future__ import annotations

from .base import (
    CONTRACT_REVISION,
    SCHEMA_VERSION,
    Contract,
    SchemaVersion,
    VersionedContract,
    content_hash_of,
)
from .enums import (
    TERMINAL_RECOMMENDATION_STATUSES,
    ActionCode,
    ApprovalStatus,
    CalibrationStatus,
    CapabilityState,
    CheckStatus,
    CoverageStatus,
    DeploymentProfile,
    EligibilityState,
    ExecutionMatch,
    FailureCategory,
    FlagState,
    JobStatus,
    OperatorAction,
    PlanningStatus,
    Provenance,
    Quality,
    ReasonCode,
    RecommendationStatus,
    RivalIntention,
    SessionCommandKind,
    SessionMode,
    StreamEventType,
)
from .errors import ApiError, ApiErrorResponse, ErrorCode
from .estimate import (
    EstimateQuality,
    IntentionWeights,
    OwnCarEstimate,
    RaceContext,
    RivalBelief,
    StateEstimate,
)
from .events import (
    EstimateUpdatedPayload,
    ExecutionObservedPayload,
    ExperimentProgressPayload,
    HeartbeatPayload,
    QualityChangedPayload,
    RecommendationUpdatedPayload,
    ResyncRequiredPayload,
    RuleContextChangedPayload,
    SnapshotPayload,
    StreamEnvelope,
    StreamEnvelopeAdapter,
    TelemetrySeries,
    TelemetryViewPayload,
)
from .lifecycle import (
    CheckpointDefinition,
    ControlLease,
    ExecutionEvent,
    LifecycleTransition,
    OperatorEvent,
    OutcomeRecord,
    SessionCommand,
)
from .models import (
    BenchmarkComparison,
    BenchmarkReport,
    CalibrationReport,
    ExperimentJob,
    ExperimentManifest,
    FeatureField,
    FeatureManifest,
    ModelManifest,
    NormalizerManifest,
    PromotionPolicy,
    RewardManifest,
    SupportThresholds,
)
from .planning import (
    CandidatePlan,
    CheckpointOutcome,
    ObjectiveTerms,
    PlanningResult,
    ProfileSegment,
    Recommendation,
    ScenarioOutcome,
    Trigger,
)
from .quantities import (
    EnsembleBelief,
    IntervalValue,
    ProbabilityStatement,
    ScalarValue,
    WeightedSample,
)
from .registry import CHANNELS, CHANNELS_BY_NAME, ChannelSpec, channel, is_registered
from .rules import (
    ApplicableLimits,
    ConstraintCheck,
    ConstraintResult,
    CoverageEntry,
    DetectionLine,
    PowerCurve,
    PowerCurvePoint,
    RuleContext,
    RuleManifest,
    RuleReference,
)
from .session import (
    RuntimeCapabilities,
    SessionManifest,
    SessionSnapshot,
    SessionSummary,
    SnapshotReference,
)
from .telemetry import (
    ChannelQuality,
    QualityEvent,
    RawSourcePacket,
    SourceCapability,
    TelemetryChunkManifest,
    TelemetryEvent,
)

__version__ = "0.1.0"

__all__ = [
    "CHANNELS",
    "CHANNELS_BY_NAME",
    "CONTRACT_REVISION",
    "SCHEMA_VERSION",
    "TERMINAL_RECOMMENDATION_STATUSES",
    "ActionCode",
    "ApiError",
    "ApiErrorResponse",
    "ApplicableLimits",
    "ApprovalStatus",
    "BenchmarkComparison",
    "BenchmarkReport",
    "CalibrationReport",
    "CalibrationStatus",
    "CandidatePlan",
    "CapabilityState",
    "ChannelQuality",
    "ChannelSpec",
    "CheckStatus",
    "CheckpointDefinition",
    "CheckpointOutcome",
    "ConstraintCheck",
    "ConstraintResult",
    "Contract",
    "ControlLease",
    "CoverageEntry",
    "CoverageStatus",
    "DeploymentProfile",
    "DetectionLine",
    "EligibilityState",
    "EnsembleBelief",
    "ErrorCode",
    "EstimateQuality",
    "EstimateUpdatedPayload",
    "ExecutionEvent",
    "ExecutionMatch",
    "ExecutionObservedPayload",
    "ExperimentJob",
    "ExperimentManifest",
    "ExperimentProgressPayload",
    "FailureCategory",
    "FeatureField",
    "FeatureManifest",
    "FlagState",
    "HeartbeatPayload",
    "IntentionWeights",
    "IntervalValue",
    "JobStatus",
    "LifecycleTransition",
    "ModelManifest",
    "NormalizerManifest",
    "ObjectiveTerms",
    "OperatorAction",
    "OperatorEvent",
    "OutcomeRecord",
    "OwnCarEstimate",
    "PlanningResult",
    "PlanningStatus",
    "PowerCurve",
    "PowerCurvePoint",
    "ProbabilityStatement",
    "ProfileSegment",
    "PromotionPolicy",
    "Provenance",
    "Quality",
    "QualityChangedPayload",
    "QualityEvent",
    "RaceContext",
    "RawSourcePacket",
    "ReasonCode",
    "Recommendation",
    "RecommendationStatus",
    "RecommendationUpdatedPayload",
    "ResyncRequiredPayload",
    "RewardManifest",
    "RivalBelief",
    "RivalIntention",
    "RuleContext",
    "RuleContextChangedPayload",
    "RuleManifest",
    "RuleReference",
    "RuntimeCapabilities",
    "ScalarValue",
    "ScenarioOutcome",
    "SchemaVersion",
    "SessionCommand",
    "SessionCommandKind",
    "SessionManifest",
    "SessionMode",
    "SessionSnapshot",
    "SessionSummary",
    "SnapshotPayload",
    "SnapshotReference",
    "SourceCapability",
    "StateEstimate",
    "StreamEnvelope",
    "StreamEnvelopeAdapter",
    "StreamEventType",
    "SupportThresholds",
    "TelemetryChunkManifest",
    "TelemetryEvent",
    "TelemetrySeries",
    "TelemetryViewPayload",
    "Trigger",
    "VersionedContract",
    "WeightedSample",
    "channel",
    "content_hash_of",
    "is_registered",
]
