"""Shared synthetic builders for the data-module tests.

Everything here is synthetic. No fixture in this directory is measured
telemetry, a real session, or redistributed third-party data.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import pytest

from afterlap_contracts import Provenance, SessionMode
from afterlap_core.data import (
    IngestionPipeline,
    ObservationRecord,
    SourcePipelineConfig,
    public_replay_capability,
    public_replay_mapping,
    simulator_capability,
    simulator_mapping,
)
from afterlap_core.timebase import ClockMapping

SESSION_ID = "synthetic-battle-001"
CAR_ID = "car-01"
SIM_SOURCE = "simulator"
PUBLIC_SOURCE = "public-replay"

SYNTHETIC_FIXTURE_NOTICE = (
    "Synthetic fixture generated by the AFTERLAP test suite. Not measured telemetry, "
    "not a real session, not redistributed public data."
)


def observation(
    sequence: int,
    source_time_s: float,
    fields: Mapping[str, Any] | None = None,
    *,
    source_id: str = SIM_SOURCE,
    car_id: str = CAR_ID,
    received_time_s: float | None = None,
    restart_marker: bool = False,
) -> ObservationRecord:
    return ObservationRecord(
        source_id=source_id,
        car_id=car_id,
        source_time_s=source_time_s,
        source_sequence=sequence,
        fields=dict(fields) if fields is not None else {"speed_mps": 70.0},
        received_time_s=received_time_s,
        restart_marker=restart_marker,
    )


def simulator_config(
    *,
    reorder_window_s: float = 0.2,
    source_id: str = SIM_SOURCE,
    session_id: str = SESSION_ID,
    rate_hz: float = 20.0,
    clock_uncertainty_s: float = 0.0,
    offset_s: float = 0.0,
) -> SourcePipelineConfig:
    return SourcePipelineConfig(
        session_id=session_id,
        source_id=source_id,
        mapping=simulator_mapping(source_id),
        capability=simulator_capability(source_id, rate_hz=rate_hz),
        provenance=Provenance.SIMULATED,
        clock=ClockMapping(source_id=source_id, offset_s=offset_s, uncertainty_s=clock_uncertainty_s),
        reorder_window_s=reorder_window_s,
    )


def public_config(
    *,
    reorder_window_s: float = 1.0,
    source_id: str = PUBLIC_SOURCE,
    session_id: str = SESSION_ID,
) -> SourcePipelineConfig:
    return SourcePipelineConfig(
        session_id=session_id,
        source_id=source_id,
        mapping=public_replay_mapping(source_id),
        capability=public_replay_capability(source_id),
        provenance=Provenance.MEASURED,
        clock=ClockMapping(source_id=source_id, offset_s=0.0, uncertainty_s=0.5),
        reorder_window_s=reorder_window_s,
    )


@pytest.fixture
def sim_pipeline() -> IngestionPipeline:
    return IngestionPipeline(simulator_config())


@pytest.fixture
def public_pipeline() -> IngestionPipeline:
    return IngestionPipeline(public_config())


def write_public_archive(path: Path, rows: Sequence[Mapping[str, Any]]) -> Path:
    """Write a synthetic OpenF1-shaped JSON archive.

    Field names imitate the public car-data shape (source register D01) so the
    mapping table is exercised realistically. The values are invented.
    """
    payload = {
        "notice": SYNTHETIC_FIXTURE_NOTICE,
        "rows": [dict(row) for row in rows],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def public_row(
    session_time: float,
    speed_kph: float,
    *,
    driver_number: int = 1,
    drs: int = 12,
    n_gear: int = 7,
) -> dict[str, Any]:
    return {
        "session_time": session_time,
        "date": "2026-09-08T12:00:00+00:00",
        "driver_number": driver_number,
        "speed": speed_kph,
        "n_gear": n_gear,
        "rpm": 11000,
        "throttle": 99,
        "brake": 0,
        "drs": drs,
    }


def sim_session_mode() -> SessionMode:
    return SessionMode.SIMULATION
